-- FV Hats E-commerce Schema (Full CMS)

-- Eliminar tablas si existen para evitar errores de columnas faltantes
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS testimonials CASCADE;
DROP TABLE IF EXISTS site_content CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

-- Table: products
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    rich_description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    image TEXT NOT NULL,
    category TEXT NOT NULL,
    stock INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: product_images (gallery)
CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: testimonials
CREATE TABLE testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    text TEXT NOT NULL,
    rating INTEGER DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
    avatar_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: site_content (key-value for landing page texts)
CREATE TABLE site_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_key TEXT UNIQUE NOT NULL,
    content_value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: settings
CREATE TABLE settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whatsapp_number TEXT NOT NULL,
    contact_email TEXT,
    contact_phone TEXT,
    promo_banner_text TEXT,
    hero_banner_url TEXT,
    logo_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: orders (Optional for future use)
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT,
    customer_phone TEXT,
    total_amount NUMERIC(10, 2) NOT NULL,
    status TEXT DEFAULT 'pending',
    items JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert Initial Settings
INSERT INTO settings (whatsapp_number, contact_email, contact_phone, promo_banner_text)
VALUES ('5212345678900', 'contacto@fvhats.com', '+52 1 234 567 8900', 'Envíos gratis en compras mayores a $99.00');

-- Insert default site content
INSERT INTO site_content (content_key, content_value) VALUES
  ('hero_badge', 'Nueva Colección 2026'),
  ('hero_title_line1', 'ELEVA TU ESTILO'),
  ('hero_title_line2', 'A OTRO NIVEL'),
  ('hero_subtitle', 'Gorras premium con diseños exclusivos. Encuentra la pieza perfecta que define tu actitud.'),
  ('hero_cta_primary', 'Ver Catálogo'),
  ('hero_cta_secondary', 'Más Vendidos'),
  ('feature_1_title', 'Calidad Premium'),
  ('feature_1_desc', 'Materiales de la más alta calidad para mayor durabilidad.'),
  ('feature_2_title', 'Envíos Rápidos'),
  ('feature_2_desc', 'Entrega segura a todo el país en tiempo récord.'),
  ('feature_3_title', 'Compra Segura'),
  ('feature_3_desc', 'Checkout fácil y rápido directo desde WhatsApp.'),
  ('featured_badge', 'Selección Exclusiva'),
  ('featured_title', 'MÁS VENDIDOS'),
  ('cta_title', 'ÚNETE A LA FAMILIA FV'),
  ('cta_subtitle', 'Recibe acceso anticipado a nuevas colecciones y descuentos exclusivos.'),
  ('footer_description', 'Elevando tu estilo con la mejor selección de gorras premium. Diseño, calidad y actitud en cada pieza.')
ON CONFLICT (content_key) DO NOTHING;

-- Policies for anon reads
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public products are viewable by everyone." ON products FOR SELECT USING (true);
CREATE POLICY "Authenticated users can manage products." ON products FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE product_images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public product images are viewable by everyone." ON product_images FOR SELECT USING (true);
CREATE POLICY "Authenticated users can manage product images." ON product_images FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public testimonials are viewable by everyone." ON testimonials FOR SELECT USING (true);
CREATE POLICY "Authenticated users can manage testimonials." ON testimonials FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public site content is viewable by everyone." ON site_content FOR SELECT USING (true);
CREATE POLICY "Authenticated users can manage site content." ON site_content FOR ALL USING (auth.role() = 'authenticated');

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Settings are viewable by everyone." ON settings FOR SELECT USING (true);
CREATE POLICY "Authenticated users can manage settings." ON settings FOR ALL USING (auth.role() = 'authenticated');
